"""empty message

Revision ID: 4cf236a7787a
Revises: 
Create Date: 2025-08-31 23:13:53.546126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf236a7787a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.Unicode(length=17), nullable=False),
    sa.Column('timeslot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeslot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('created', 'confirmed', 'canceled', name='appointmentstatus'), nullable=False),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('timeslot_start < timeslot_end', name=op.f('ck_appointments_check_timeslot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.execute("DROP TYPE IF EXISTS appointmentstatus;")
    # ### end Alembic commands ###
