version: "4.2"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/app.env
    ports:
      - "5432:5432"
    networks:
      - appointment
  app:
    build: .
    env_file:
      - ./envs/app.env
    command: ...
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appointment

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - appointment
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  appointment:
    driver: bridge

